name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install && spago install

      - name: Build project
        run: spago build

      - name: Build example
        run: make run-example

      - name: Run tests
        run: spago test
